import Link from 'next/link'
import React from 'react'

const FooterLift = () => {
  return (
  <div className='bg-black'>
    <footer className="inset-x-0 mx-auto z-[200] w-full pt-3 px-4 sm:px-6 lg:px-8 border-t border-neutral-900">
      <div className="px-5 py-8 max-w-7xl mx-auto flex items-center sm:flex-row flex-col">
        <Link href='/' className="flex text-lg items-center text-white mb-4 md:mb-0">
          <img src='/logo.png' loading="lazy" className="lg:w-52  md:w-40  sm:w-48  w-44  my-6" alt="Logo Brinpage"/>
        </Link>
        <p className="text-sm text-neutral-200 sm:ml-4 sm:pl-4 text-center sm:border-l border-neutral-400 sm:py-2 sm:mt-0 mt-4">© 2025 LiftCode AI  by <a href="https://brinpage.com/" className='hover:underline hover:text-neutral-500'>BrinPage</a> — All rights reserved.</p>
        <div className='inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start'>
          <Link href="/"className='mx-2 text-sm text-neutral-200 hover:text-neutral-600 hover:underline transition font-medium'>Home</Link>
          {/* <a href='/news' className='mx-2 text-sm text-neutral-200 hover:text-neutral-600 hover:underline transition font-medium'>News</a>
          <a href='/chat' className='mx-2 text-sm text-neutral-200 hover:text-neutral-600 hover:underline transition font-medium'>Components</a> */}
          <a href='/pricing' className='mx-2 text-sm text-neutral-200 hover:text-neutral-600 hover:underline transition font-medium'>Pricing</a>
          <a href='/terms' className='mx-2 text-sm text-neutral-200 hover:text-neutral-600 hover:underline transition font-medium'>Terms and Conditions</a>
        </div>
      </div>
      <div className="inset-x-0 max-w-7xl mx-auto pb-12">
        <div className="mx-auto items-center max-w-[85rem]">
          <p className='text-neutral-200 text-sm max-w-[85rem] sm:mx-0 mx-2 px-4 pb-4'>BrinPage is not responsible for any direct, indirect, incidental, consequential, or special damages, including but not limited to loss of data, financial losses, business interruption, or any other damage arising from the use, misuse, or inability to use our services, platforms, or tools. Users are solely responsible for ensuring the proper and ethical use of our solutions, as well as for monitoring any critical information processed through our services.</p>
          <p className='text-neutral-200 text-sm max-w-[85rem] sm:mx-0 mx-2 px-4 pb-4'>While we strive to offer accurate, reliable, and continuously improving AI-based solutions, we do not guarantee absolute accuracy, uninterrupted availability, or infallibility in the results generated by our technologies. The decisions made based on our services are the full responsibility of the user, and BrinPage shall not be held liable for any consequences derived from such decisions.</p>
          <p className='text-neutral-200 text-sm max-w-[85rem] sm:mx-0 mx-2 px-4 pb-4'>The content, features, functionalities, and tools provided by BrinPage are protected by intellectual property laws, and all associated rights are reserved. Unauthorized reproduction, distribution, modification, or commercial use of any of our proprietary technologies, algorithms, or software components is strictly prohibited.</p>
          <p className='text-neutral-200 text-sm max-w-[85rem] sm:mx-0 mx-2 px-4 pb-4'>By accessing and using our services, you acknowledge and accept these conditions. We strongly recommend reviewing our <a href="/legal" className="text-blue-500 underline">terms and conditions</a> and Privacy Policy, where you will find more detailed information regarding your rights, responsibilities, and data processing practices. If you have any questions, concerns, or require assistance, you can contact our support team by filling out the following form: <a href="https://brinpage.com/contact" className="text-blue-500">contact form</a>.</p>
        </div>
      </div>
      </footer>
  </div> 
  )
}

export default FooterLift

// <p className='text-white text-sm max-w-[85rem] sm:mx-0 mx-2 px-4 pb-4'>We are not responsible for any damage or harm that our services may cause, remember to monitor important information. If you have any questions, you can contact our support team by filling out the following form: <a href="/contact" className="text-[#ff7b00]">contact form</a>. All rights related to the content, functionalities and tools of our solutions are reserved. The use of our services implies acceptance of our <a href="/legal" className="text-[#ff7b00] underline">terms and conditions</a>, please read them carefully.</p>
